### ISSUE TITLE
Operator needs to check for permissions

### ISSUE THREAD

**Issue by wkulhanek** [redhat-gpte-devopsautomation/argocd-namespace-operator#1]
Current operator will add the label to any namespace.
Need to check if the requester has access to the ArgoCD namespace that they are requesting access to. Otherwise update the status of the CR with an error and an error message.

**Comment by christianh814** [comment]
This is how oauth-proxy does it: [LINK](https://github.com/openshift/oauth-proxy#require-specific-permissions-to-login-via-oauth-with---openshift-sarjson)

**Comment by ludovicmotte** [comment]
Hi @wkulhanek , I would need this fix. And perhaps could help for the implementation ;-)
How do you see the check ?
We can't identify the requester, do we ?

One idea I had: could we check if we found a user that is admin on both namespaces ?

**Comment by christianh814** [comment]
@wkulhanek Does your operator know who's requesting it? It looks like you can check `.metadata.annotations.openshift\.io\/requester`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: developer
    openshift.io/sa.scc.mcs: s0:c26,c10
    openshift.io/sa.scc.supplemental-groups: 1000670000/10000
    openshift.io/sa.scc.uid-range: 1000670000/10000
  creationTimestamp: "2023-03-30T17:23:17Z"
  labels:
    kubernetes.io/metadata.name: apples
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.24
  name: apples
  resourceVersion: "39195"
  uid: c3d99a83-1946-4fe3-875e-52e22adf013a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
